language: ruby
rvm:
  - 2.3.1

before_install:
  - openssl aes-256-cbc -K $encrypted_e403eabacc39_key -iv $encrypted_e403eabacc39_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - chmod +x ./publi.sh
  - bin/setup

script:
  - rm -rf _site/
  - rm -rf .asset-cache/
  - bundle exec jekyll build
  - cp CNAME _site/
  - ./publi.sh


# branch whitelist, only for GitHub Pages
branches:
  only:
  - develop

sudo: false # route your build to the container-based infrastructure for a faster build
