language: ruby
rvm:
  - 2.2
before_install:

before_install:
  - chmod +x ./publi.sh
  - bundle install
  - openssl aes-256-cbc -K $encrypted_e403eabacc39_key -iv $encrypted_e403eabacc39_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
script:
  - publi.sh


# branch whitelist, only for GitHub Pages
branches:
  only:
  - develop

sudo: false # route your build to the container-based infrastructure for a faster build
