language: java

before_install:
  openssl aes-256-cbc -K $encrypted_e403eabacc39_key -iv $encrypted_e403eabacc39_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

script: echo $encrypted_e403eabacc39_key; echo $encrypted_e403eabacc39_iv; gradle jbake publishGhPages
