language: ruby
rvm:
  - 2.2

before_install:
  - chmod +x ./publi.sh
  - openssl aes-256-cbc -K $encrypted_e403eabacc39_key -iv $encrypted_e403eabacc39_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

script:
  - rm -rf _site/
  - bundle exec jekyll build
  - ./publi.sh


# branch whitelist, only for GitHub Pages
branches:
  only:
  - develop

sudo: false # route your build to the container-based infrastructure for a faster build
