source "https://rubygems.org"

gem "autoprefixer-rails"
gem "html-proofer"
gem "jekyll", "~> 3.7.4"
gem "jekyll-assets"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "mini_magick"
gem "sass"
gem "uglifier"
gem "sprockets", "~> 3.7"
